### ISSUE TITLE
Not able to connect my HX962K

### ISSUE THREAD

**Issue by jampez77** [GrumpyMeow/sonicare-ble-hacs#12]
My toothbrush is discovered but won't then go on to connect.

```
2023-06-26 15:59:52.302 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: None
2023-06-26 15:59:52.304 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 15:59:52.306 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connection already in progress, waiting for it to complete; RSSI: None
2023-06-26 15:59:52.422 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 344, in establish_connection
    await client.connect(
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 272, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 263, in connect
    await self.get_services(
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 649, in get_services
    self.services = await manager.get_services(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 581, in get_services
    await self._wait_for_services_discovery(device_path)
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 686, in _wait_for_services_discovery
    raise BleakError("failed to discover services, device disconnected")
bleak.exc.BleakError: failed to discover services, device disconnected
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sonicare_bletb/sonicare_bletb.py", line 330, in _reconnect
    await self._ensure_connected()
  File "/usr/local/lib/python3.11/site-packages/sonicare_bletb/sonicare_bletb.py", line 314, in _ensure_connected
    client = await establish_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 421, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 320, in _raise_if_needed
    raise BleakConnectionError(msg) from exc
bleak_retry_connector.BleakConnectionError: Philips Sonicare - 24:E5:AA:A3:E5:E4: Failed to connect: failed to discover services, device disconnected
2023-06-26 15:59:52.429 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: None
2023-06-26 15:59:54.293 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 15:59:56.295 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 15:59:59.054 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Init
2023-06-26 15:59:59.055 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 15:59:59.058 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: None
2023-06-26 16:00:05.306 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
```

**Comment by jampez77** [comment]
And just like that it let me `connect` to the brush, however all entities are unavailable and remain so during use. Here is the entire log while the brush was in use:

```
2023-06-26 16:04:45.240 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:04:45.241 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:04:45.243 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:04:45.244 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:04:45.246 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:04:45.249 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:04:45.251 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:04:45.253 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:04:45.255 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:04:46.735 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:04:46.737 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:04:46.740 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:04:46.742 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
0:00:01
2023-06-26 16:04:53.616 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:04:53.617 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:04:53.617 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:04:53.618 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:04:53.620 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:04:55.150 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:04:55.152 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:04:55.153 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:04:55.154 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:04:56.826 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:05:00.835 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:05:01.212 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:05:01.213 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:05:01.214 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:05:01.216 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:05:01.217 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:05:02.708 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:05:02.709 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:05:02.710 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:05:02.712 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:05:09.796 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:05:09.797 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:05:09.798 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:05:09.798 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:05:09.799 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:05:10.877 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:05:11.329 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:05:11.331 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:05:11.332 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:05:11.333 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:05:12.878 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:05:47.445 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:05:47.446 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:05:47.448 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:05:47.449 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:05:47.450 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:05:48.942 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:05:48.944 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:05:48.946 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:05:48.948 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:05:51.913 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:05:55.205 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:05:55.207 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:05:55.209 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:05:55.210 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:05:55.212 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:05:56.739 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:05:56.742 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:05:56.744 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:05:56.747 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:06:03.826 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:06:03.828 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:06:03.829 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:06:03.831 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:06:03.833 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:06:04.929 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:06:05.286 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:06:05.288 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:06:05.289 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:06:05.290 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:06:07.936 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:06:12.099 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:06:12.101 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:06:12.103 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:06:12.105 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:06:12.108 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:06:13.595 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:06:13.597 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:06:13.599 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:06:13.601 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:06:20.273 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:06:20.275 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:06:20.277 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:06:20.279 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:06:20.281 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:06:20.954 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:06:21.769 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:06:21.771 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:06:21.773 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:06:21.775 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:06:23.957 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:06:29.476 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:06:29.478 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:06:29.480 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:06:29.481 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:06:29.483 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:06:30.974 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:06:30.977 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:06:30.979 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:06:30.981 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:06:32.965 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:06:38.064 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:06:38.066 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:06:38.067 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:06:38.069 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:06:38.070 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:06:39.561 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:06:39.563 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:06:39.565 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:06:39.567 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:06:56.378 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:06:56.379 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:06:56.380 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:06:56.380 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:06:56.381 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:06:56.996 WARNING (MainThread) [homeassistant.components.sensor] Updating rest sensor took longer than the scheduled update interval 0:00:01
2023-06-26 16:06:58.439 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:06:58.440 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:06:58.442 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:06:58.443 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:07:06.061 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:07:06.062 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:07:06.063 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:07:06.064 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:07:06.065 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:07:07.632 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:07:07.634 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:07:07.637 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:07:07.639 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:07:14.579 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:07:14.580 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:07:14.582 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:07:14.583 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:07:14.585 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:07:16.050 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:07:16.052 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:07:16.055 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:07:16.057 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
2023-06-26 16:07:23.138 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connected; RSSI: -64
2023-06-26 16:07:23.139 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensured connection - initialising
2023-06-26 16:07:23.140 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: initialise
2023-06-26 16:07:23.141 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Subscribe to notifications; RSSI: -64
2023-06-26 16:07:23.142 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Get_services
2023-06-26 16:07:24.670 WARNING (MainThread) [custom_components.sonicare_bletb.coordinator] _async_handle_disconnect
2023-06-26 16:07:24.672 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Device unexpectedly disconnected; RSSI: -64
2023-06-26 16:07:24.674 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] ensuring connection
2023-06-26 16:07:24.676 WARNING (MainThread) [sonicare_bletb.sonicare_bletb] Philips Sonicare: Connecting; RSSI: -64
```

**Comment by jampez77** [comment]
I just had my toothbrush replaced under warranty with a HX960K and the same problem persists

**Comment by bcutter** [comment]
Please provide information on your specivic bluetooth environment: how are you trying to connect your toothbrush with HA? Are you using a Bluetooth Proxy (https://esphome.github.io/bluetooth-proxies/)?

You might want to have a look at this issue:

https://github.com/GrumpyMeow/sonicare-ble-hacs/issues/14

**Comment by jampez77** [comment]
Hi, I'm not using any BT proxies. My toothbrush is connected directly to HA via this dongle. 

https://www.amazon.co.uk/gp/product/B08SC9M9K3/
